---
title: Charnsak2.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Charnsak Github
description: Lecturer
avatar: https://scontent.fbkk14-1.fna.fbcdn.net/v/t1.0-1/p160x160/14611013_1128270937263309_6403202336549863855_n.jpg?oh=0b73422cff91e8227ee3ebc1131fcf74&oe=5A59804D
footer-links:
  dribbble: 
  email: charnsak@live.com
  facebook: Charnsak
  flickr: 
  github: barryclark/jekyll-now
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: charnsak
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: 
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
